params = {
  "duke" : {
    "mu" : 10,
    "l1Sparsity": 0.5,
    "PDBFW_iter": 100,
    "PDBFW_l0Sparsity": 500,
    "PDBFW_dualSparsity": 44,
    "PDBFW_delta": 20,
    "PDBFW_eta": 0.5,
    "PDBFW_L": 1,
    "FW_iter": 500,
    "FW_eta": 0.5,
    "AccPG_iter": 100,
    "AccPG_eta": 1.5,
    "STORC_iter": 10,
    "STORC_small_data": 1,
    "STORC_L": 0.1,
    "SVRG_iter": 5,
    "SVRG_small_data": 1,
    "SVRG_eta": 5,
    "SCGS_iter": 50,
    "SCGS_L": 0.5
  },
  "rcv" : {
    "mu" : 10,
    "l1Sparsity": 300,
    "PDBFW_iter": 200,
    "PDBFW_l0Sparsity": 3000,
    "PDBFW_dualSparsity": 6000,
    "PDBFW_delta": 30,
    "PDBFW_eta": 0.5,
    "PDBFW_L": 3,
    "FW_iter": 2000,
    "FW_eta": 0.4,
    "AccPG_iter": 500,
    "AccPG_eta": 100,
    "SVRF_iter": 12,
    "SVRF_eta": 0.5,
    "STORC_iter": 12,
    "STORC_small_data": 0,
    "STORC_L": 1,
    "SVRG_iter": 22,
    "SVRG_small_data": 0,
    "SVRG_eta": 40,
    "SCGS_iter": 800,
    "SCGS_L": 10
  }
}
